# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-24 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, ''), (1, '男♂'), (2, '女♀'), (3, '⚧')], default='0', max_length=6, verbose_name='性别'),
        ),
    ]
