# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-24 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=128)),
                ('private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '分类',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('private', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('referer', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'PIN',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('django_images.image',),
        ),
        migrations.AddField(
            model_name='pin',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pin', to='core.Image'),
        ),
    ]
