# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-24 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200424_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
