# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-29 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pin_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='likes',
        ),
        migrations.AddField(
            model_name='pin',
            name='likes_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
