# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-24 02:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_board_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-published',), 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='pin',
            options={'ordering': ('-published',), 'verbose_name_plural': 'PIN'},
        ),
        migrations.AddField(
            model_name='pin',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='pin_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.User'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pin', to='core.Image'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.User', verbose_name='创建时间'),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='board',
            index_together=set([]),
        ),
    ]
